-- UIDAI Meetings & MoM Governance Module - initial schema
-- All timestamps are stored in UTC (timestamptz).

-- ------------------------------------------------------------------
-- Configurable meeting types (MEET-FR-02.4)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS meeting_type (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(50)  NOT NULL UNIQUE,
    display_name      VARCHAR(150) NOT NULL,
    description       VARCHAR(500),
    requires_approval BOOLEAN      NOT NULL DEFAULT TRUE,
    active            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_by        VARCHAR(100),
    created_at        TIMESTAMPTZ,
    updated_by        VARCHAR(100),
    updated_at        TIMESTAMPTZ
);

-- ------------------------------------------------------------------
-- Meetings (MEET-FR-01 .. MEET-FR-03)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS meeting (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(250)  NOT NULL,
    meeting_date  DATE          NOT NULL,
    start_time    TIME          NOT NULL,
    end_time      TIME          NOT NULL,
    description   VARCHAR(5000),
    meeting_link  VARCHAR(1000),
    project_id    VARCHAR(64)   NOT NULL,
    status        VARCHAR(30)   NOT NULL,
    created_by    VARCHAR(100),
    created_at    TIMESTAMPTZ,
    updated_by    VARCHAR(100),
    updated_at    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_meeting_project ON meeting (project_id);
CREATE INDEX IF NOT EXISTS idx_meeting_date ON meeting (meeting_date);

CREATE TABLE IF NOT EXISTS meeting_participant (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id       BIGINT       NOT NULL REFERENCES meeting (id),
    user_id          VARCHAR(100) NOT NULL,
    participant_role VARCHAR(100),
    mandatory        BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_participant_meeting_user UNIQUE (meeting_id, user_id)
);

-- ------------------------------------------------------------------
-- Standardized MoM templates (MEET-FR-05.1)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mom_template (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150)  NOT NULL UNIQUE,
    description VARCHAR(500),
    structure   VARCHAR(8000) NOT NULL,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_by  VARCHAR(100),
    created_at  TIMESTAMPTZ,
    updated_by  VARCHAR(100),
    updated_at  TIMESTAMPTZ
);

-- ------------------------------------------------------------------
-- Minutes of Meeting (MEET-FR-04, MEET-FR-05)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS minutes_of_meeting (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id  BIGINT        NOT NULL REFERENCES meeting (id),
    template_id BIGINT        REFERENCES mom_template (id),
    title       VARCHAR(250)  NOT NULL,
    content     VARCHAR(20000),
    status      VARCHAR(30)   NOT NULL,
    created_by  VARCHAR(100),
    created_at  TIMESTAMPTZ,
    updated_by  VARCHAR(100),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT uk_mom_meeting UNIQUE (meeting_id)
);

CREATE TABLE IF NOT EXISTS mom_decision (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mom_id        BIGINT        NOT NULL REFERENCES minutes_of_meeting (id),
    description   VARCHAR(4000) NOT NULL,
    owner_user_id VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS mom_risk (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mom_id        BIGINT        NOT NULL REFERENCES minutes_of_meeting (id),
    description   VARCHAR(4000) NOT NULL,
    severity      VARCHAR(20)   NOT NULL,
    mitigation    VARCHAR(4000),
    owner_user_id VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS action_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mom_id              BIGINT        NOT NULL REFERENCES minutes_of_meeting (id),
    description         VARCHAR(4000) NOT NULL,
    assigned_to_user_id VARCHAR(100)  NOT NULL,
    due_date            DATE,
    status              VARCHAR(30)   NOT NULL,
    linked_task_id      BIGINT,
    linked_milestone_id BIGINT,
    linked_ticket_id    VARCHAR(100),
    created_by          VARCHAR(100),
    created_at          TIMESTAMPTZ,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_action_assignee ON action_item (assigned_to_user_id);
CREATE INDEX IF NOT EXISTS idx_action_status ON action_item (status);

CREATE TABLE IF NOT EXISTS action_item_comment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_item_id    BIGINT        NOT NULL REFERENCES action_item (id),
    parent_comment_id BIGINT        REFERENCES action_item_comment (id),
    author_user_id    VARCHAR(100)  NOT NULL,
    content           VARCHAR(4000) NOT NULL,
    created_at        TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_comment_action ON action_item_comment (action_item_id);
CREATE INDEX IF NOT EXISTS idx_comment_parent ON action_item_comment (parent_comment_id);

CREATE TABLE IF NOT EXISTS timeline_extension_request (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_item_id       BIGINT        NOT NULL REFERENCES action_item (id),
    previous_due_date    DATE,
    requested_due_date   DATE          NOT NULL,
    justification        VARCHAR(4000) NOT NULL,
    status               VARCHAR(20)   NOT NULL,
    requested_by_user_id VARCHAR(100)  NOT NULL,
    requested_at         TIMESTAMPTZ   NOT NULL,
    decided_by_user_id   VARCHAR(100),
    decision_comment     VARCHAR(2000),
    decided_at           TIMESTAMPTZ
);

-- ------------------------------------------------------------------
-- Immutable audit trail (MEET-FR-01.3, MEET-FR-04.5)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action       VARCHAR(50)   NOT NULL,
    entity_type  VARCHAR(50)   NOT NULL,
    entity_id    BIGINT        NOT NULL,
    performed_by VARCHAR(100)  NOT NULL,
    performed_at TIMESTAMPTZ   NOT NULL,
    details      VARCHAR(2000)
);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_at ON audit_log (performed_at);
