-- UIDAI Meetings & MoM Governance Module - consolidated initial schema.
-- Single baseline migration that creates every table in its final shape and
-- seeds the reference data. All timestamps are stored in UTC (timestamptz).

-- ------------------------------------------------------------------
-- Configurable meeting types (MEET-FR-02.4)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS meeting_type (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(50)  NOT NULL UNIQUE,
    display_name      VARCHAR(150) NOT NULL,
    description       VARCHAR(500),
    requires_approval BOOLEAN      NOT NULL DEFAULT TRUE,
    active            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_by        VARCHAR(100),
    created_at        TIMESTAMPTZ,
    updated_by        VARCHAR(100),
    updated_at        TIMESTAMPTZ
);

-- ------------------------------------------------------------------
-- Standardized MoM templates (MEET-FR-05.1)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mom_template (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150)  NOT NULL UNIQUE,
    description VARCHAR(500),
    structure   VARCHAR(8000) NOT NULL,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_by  VARCHAR(100),
    created_at  TIMESTAMPTZ,
    updated_by  VARCHAR(100),
    updated_at  TIMESTAMPTZ
);

-- ------------------------------------------------------------------
-- Meetings (MEET-FR-01 .. MEET-FR-03)
-- id is a UUID; meeting_code is a human-readable M<n> drawn from a sequence.
-- The activity_* columns link the meeting to the project activity created for it
-- in the external (Python) project service (UUIDs stored as text). project_code /
-- project_name cache the resolved project info. attachments holds the attachment
-- metadata returned by the activity-create API (id, filename, url, ...).
-- ------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS meeting_code_seq;

CREATE TABLE IF NOT EXISTS meeting (
    id                    UUID          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    meeting_code          VARCHAR(30),
    title                 VARCHAR(250)  NOT NULL,
    meeting_date          DATE          NOT NULL,
    start_time            TIME          NOT NULL,
    end_time              TIME          NOT NULL,
    description           VARCHAR(5000),
    meeting_link          VARCHAR(1000),
    project_id            VARCHAR(64)   NOT NULL,
    project_code          VARCHAR(100),
    project_name          VARCHAR(250),
    status                VARCHAR(30)   NOT NULL,
    activity_id           VARCHAR(64),
    activity_project_id   VARCHAR(64),
    activity_milestone_id VARCHAR(64),
    activity_name         VARCHAR(250),
    activity_description  VARCHAR(5000),
    attachments           JSONB,
    created_by            VARCHAR(100),
    created_at            TIMESTAMPTZ,
    updated_by            VARCHAR(100),
    updated_at            TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_meeting_project  ON meeting (project_id);
CREATE INDEX IF NOT EXISTS idx_meeting_date     ON meeting (meeting_date);
CREATE INDEX IF NOT EXISTS idx_meeting_activity ON meeting (activity_id);

CREATE TABLE IF NOT EXISTS meeting_participant (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id       UUID         NOT NULL REFERENCES meeting (id),
    user_id          VARCHAR(100) NOT NULL,
    participant_role VARCHAR(100),
    mandatory        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_external      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_present       BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_participant_meeting_user UNIQUE (meeting_id, user_id)
);

-- ------------------------------------------------------------------
-- Minutes of Meeting (MEET-FR-04, MEET-FR-05)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS minutes_of_meeting (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id  UUID          NOT NULL REFERENCES meeting (id),
    template_id BIGINT        REFERENCES mom_template (id),
    title       VARCHAR(250)  NOT NULL,
    content     VARCHAR(20000),
    status      VARCHAR(30)   NOT NULL,
    created_by  VARCHAR(100),
    created_at  TIMESTAMPTZ,
    updated_by  VARCHAR(100),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT uk_mom_meeting UNIQUE (meeting_id)
);

CREATE TABLE IF NOT EXISTS mom_decision (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mom_id        BIGINT        NOT NULL REFERENCES minutes_of_meeting (id),
    description   VARCHAR(4000) NOT NULL,
    owner_user_id VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS mom_risk (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mom_id        BIGINT        NOT NULL REFERENCES minutes_of_meeting (id),
    description   VARCHAR(4000) NOT NULL,
    severity      VARCHAR(20)   NOT NULL,
    mitigation    VARCHAR(4000),
    owner_user_id VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS action_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mom_id              BIGINT        NOT NULL REFERENCES minutes_of_meeting (id),
    description         VARCHAR(4000) NOT NULL,
    assigned_to_user_id VARCHAR(100)  NOT NULL,
    due_date            DATE,
    status              VARCHAR(30)   NOT NULL,
    linked_task_id      BIGINT,
    linked_milestone_id BIGINT,
    linked_ticket_id    VARCHAR(100),
    linked_activity_id  VARCHAR(100),
    created_by          VARCHAR(100),
    created_at          TIMESTAMPTZ,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_action_assignee ON action_item (assigned_to_user_id);
CREATE INDEX IF NOT EXISTS idx_action_status   ON action_item (status);
CREATE INDEX IF NOT EXISTS idx_action_activity ON action_item (linked_activity_id);

CREATE TABLE IF NOT EXISTS action_item_comment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_item_id    BIGINT        NOT NULL REFERENCES action_item (id),
    parent_comment_id BIGINT        REFERENCES action_item_comment (id),
    author_user_id    VARCHAR(100)  NOT NULL,
    content           VARCHAR(4000) NOT NULL,
    created_at        TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_comment_action ON action_item_comment (action_item_id);
CREATE INDEX IF NOT EXISTS idx_comment_parent ON action_item_comment (parent_comment_id);

CREATE TABLE IF NOT EXISTS timeline_extension_request (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_item_id       BIGINT        NOT NULL REFERENCES action_item (id),
    previous_due_date    DATE,
    requested_due_date   DATE          NOT NULL,
    justification        VARCHAR(4000) NOT NULL,
    status               VARCHAR(20)   NOT NULL,
    requested_by_user_id VARCHAR(100)  NOT NULL,
    requested_at         TIMESTAMPTZ   NOT NULL,
    decided_by_user_id   VARCHAR(100),
    decision_comment     VARCHAR(2000),
    decided_at           TIMESTAMPTZ
);

-- ------------------------------------------------------------------
-- Immutable audit trail (MEET-FR-01.3, MEET-FR-04.5).
-- entity_id is VARCHAR so it can hold meeting UUIDs as well as numeric ids.
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action       VARCHAR(50)   NOT NULL,
    entity_type  VARCHAR(50)   NOT NULL,
    entity_id    VARCHAR(64)   NOT NULL,
    performed_by VARCHAR(100)  NOT NULL,
    performed_at TIMESTAMPTZ   NOT NULL,
    details      VARCHAR(2000)
);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_at     ON audit_log (performed_at);

-- ------------------------------------------------------------------
-- Reference data (MEET-FR-02 / MEET-FR-02.4, MEET-FR-05.1)
-- ------------------------------------------------------------------
INSERT INTO meeting_type (code, display_name, description, requires_approval, active, created_by, created_at)
VALUES
    ('STEERING',   'Steering Committee', 'Strategic steering meetings',                 TRUE,  TRUE, 'system', now()),
    ('GOVERNANCE', 'Governance Review',  'Programme governance and oversight meetings', TRUE,  TRUE, 'system', now()),
    ('MIGRATION',  'Migration Review',   'Data / system migration meetings',            TRUE,  TRUE, 'system', now()),
    ('ADHOC',      'Ad-hoc',             'Unscheduled / ad-hoc meetings',               FALSE, TRUE, 'system', now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO mom_template (name, description, structure, active, created_by, created_at)
VALUES (
    'UIDAI Standard MoM',
    'Default standardized Minutes-of-Meeting layout for UIDAI governance meetings',
    '{"sections":["Attendees","Agenda","Discussion","Decisions","Action Items","Risks","Next Steps"]}',
    TRUE,
    'system',
    now()
)
ON CONFLICT (name) DO NOTHING;
